### ISSUE TITLE
PHP Run Error

### ISSUE THREAD

**Issue by ChrisChinchilla** [crate/crate-sample-apps#28]
@mikethebeer I follow the instructions for running the PHP app and get this error:

<br />
<b>Strict Standards</b>:  Declaration of CrateResource::error() should be compatible with Slim\Slim::error($argument = NULL) in <b>/Users/chrisward/Workspace/crate-sample-apps/php/index.php</b> on line <b>6</b><br />
"Server up and running"

**Comment by chaudum** [comment]
seems like your're running php in strict mode.
I agree we should get rid of any warnings by enforcing strict mode using
```php
error_reporting(E_STRICT);
```

**Comment by ChrisChinchilla** [comment]
@chaudum Pretty much every time I test these things I install a language and test with default installation of the language, not completely realistic, but the best way to test I think.

So, do you want me to change something in this setup, or we need to change the application?

**Comment by chaudum** [comment]
@ChrisChinchilla we'll change the app to work with strict mode. made an impediment

**Comment by mikethebeer** [comment]
@ChrisChinchilla fixed in master https://github.com/crate/crate-sample-apps/commit/b5794eb13a7503fddb135918b748c43b65bc38f3
