### ISSUE TITLE
Sample-app UI doesn't display posts.

### ISSUE THREAD

**Issue by MaxLiko** [crate/crate-sample-apps#51]
Posts can be created and are added to the dedicated table but are not displayed in the frontend UI.
I use:
3 node cluster with docker 1.11.2
Python sample-app as backand

**Comment by mikethebeer** [comment]
reason was that you forget to import country data

```
crash < sql/schemas.sql
crash -c "COPY guestbook.countries FROM '$(pwd)/sql/countries.json'"
```
