### ISSUE TITLE
create table statement in java/documentation.md to be amended

### ISSUE THREAD

**Issue by michaelhoedl** [crate/crate-sample-apps#52]
In "crate-sample-apps/java/documentation.md", it seems that the create table statement should be amended: instead of  
`"    user OBJECT('strict') AS ( " +`
it should rather be 
` "    user OBJECT(strict) AS ( " +`
, as it seems that it's not possible to have single quotations marks for the keywords "strict" or "dynamic" when using in an "object". 
At least this did not work for me, as I get this error then:  

> SQLActionException[SQLParseException: line 4:20: mismatched input 'strict' expecting set null]

https://github.com/crate/crate-sample-apps/blob/master/java/documentation.md#executing-single-statement

**Comment by joemoe** [comment]
hi @michaelhoedl, we'll have a look at it and fix it. we are also very open to PRs. so if you find something like this don't hesitate to just fix it. thanks for reporting anyway. cheers, johannes

**Comment by joemoe** [comment]
@michaelhoedl, this is fixed now.  https://github.com/crate/crate-sample-apps/blob/master/java/documentation.md
thanks again for reporting.
