### ISSUE TITLE
Cannot import sample data

### ISSUE THREAD

**Issue by toanalien** [crate/crate-sample-apps#73]
I used the command in README.md file to import sample data but it does not affect.

```bash
$ crash -c "COPY guestbook.countries FROM '$(pwd)/sql/countries.json'"
CONNECT OK
COPY OK, 0 rows affected  (0.001 sec)
```
```
crate
number: 3.0.3
build_hash: f49bb62876bb11a5a1ebc15cdd759f3b5f15d6e2
------
crash
version: 0.23.0
```

**Comment by lukasbals** [comment]
@toanalien Is it possible that you have already imported the data? 
I tried to reproduce this message and I only got it, when I ran the command when the data was already in the table.

**Comment by toanalien** [comment]
@lukasbals Thank you for your reply. Not yet imported succeed.

**Comment by toanalien** [comment]
```bash
toanalien@Toans-MacBook-Pro $ ~/Documents/crate-sample-apps : crash < sql/schemas.sql                                  
CONNECT OK
DROP OK, 1 row affected  (0.384 sec)
CREATE OK, 1 row affected  (0.397 sec)
DROP OK, 1 row affected  (0.110 sec)
CREATE OK, 1 row affected  (0.082 sec)
DROP OK, 1 row affected  (0.257 sec)
CREATE OK, 1 row affected  (0.169 sec)

toanalien@Toans-MacBook-Pro $ ~/Documents/crate-sample-apps : crash -c "COPY guestbook.countries FROM '$(pwd)/sql/countries.json'"
CONNECT OK
COPY OK, 0 rows affected  (0.082 sec)
```

**Comment by lukasbals** [comment]
how are you running crate? (cr8, docker, ...) have you tried to reboot the db?

**Comment by toanalien** [comment]
I use docker. I connect to database from host machine, crash installed by pip.

**Comment by lukasbals** [comment]
ok ... if you are using docker you have to run the command inside the docker container

You can enter the container with the following command:
```
docker exec -it crate-container /bin/ash
```
You have to copy the countries.json file into the docker container ... and then you can run crash command in the container:

```
crash -c "COPY guestbook.countries FROM '$(pwd)/countries.json'"
```

We recommend you to use cr8, it is installable with pip.
```
cr8 run-crate <version> (e.g. latest-nightly, 3.0.5, ...)
```

**Comment by toanalien** [comment]
Great @lukasbals !!! It works. 

```bash
$ docker cp countries.json crate-container:/data
$ docker exec -it crate-container /bin/sh
$ crash -c "COPY guestbook.countries FROM '$(pwd)/countries.json'"
```
