### ISSUE TITLE
Make Go application HTTP API adhere to the specification

### ISSUE THREAD

**Issue by amotl** [crate/crate-sample-apps#91]
Dear @sergesheff,

while modernizing this repository a bit, we also ran the test suite against the Go application you contributed recently - thank you again. Unfortunately, the test suite croaks. The frontend application works well, though.

The test suite is in the `tests/` folder, and can be invoked like:
```sh
cd tests
python3 test.py --host localhost --port 8080
```

Do you think you can improve the Go application so that it honors the specification implemented by the test suite, as all other applications here are doing as well?

Because the frontend application works well, I think it might only need some minor adjustments to also cover the error paths appropriately.

With kind regards,
Andreas.

**Comment by amotl** [comment]
> I think it might only need some minor adjustments to also cover the error paths appropriately.

I've just added 8aea66eb5 to GH-92, and I think it might be similar to how the changes to the Go application might be.

**Comment by amotl** [comment]
Hi again. GH-94 has similar changes, for the `java-spring` application. It did not adhere to the specification on some spots, which has been fixed now.

**Comment by sergesheff** [comment]
Sorry, didn't know about /test folder :(
I'm not familiar to python at all, but I hope i've updated all response codes. Anyway, please let me know if i should update anything else.
Also i have one remark to the application for automated testing. Golang has many unusual requirement to how coding style. One of them is that error string can't be capitalized (https://github.com/golang/go/wiki/CodeReviewComments#error-strings).
In test python file i've noticed many places where error messages is case sensitive (ащк учфьздуЖ )

**Comment by amotl** [comment]
GH-97 works excellently, thank you very much.

**Comment by amotl** [comment]
Now there would be only one single thing left over, which I just discovered: When the program is called without any option flag, it segfaults. I think it would be nice if it could respond with a corresponding error message and the output from `go run . --help` instead.

```golang
$ go run .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x15b643e]

goroutine 1 [running]:
main.main()
	/Users/amo/dev/crate/docs/crate-sample-apps/golang/main.go:40 +0x1fe
exit status 2
```

**Comment by amotl** [comment]
I've implemented this with GH-99. Thanks again.

**Comment by amotl** [comment]
I think everything is fine now. I've even upgraded the dependencies yesterday, with eac2069. Thank you again!

**Comment by amotl** [comment]
> In test python file i've noticed many places where error messages is case sensitive (for example: 'Post with id="{}" not found'.format(id)). I've updated error messages to pass tests, but they are throwing warnings.
I'm not familiar to python, but if possible will be great to make this kind asserts will be case insensitive.

I am sorry about this detail, but I wouldn't bother about it. Apologies that it does violate some convention of Go. Can you tell me how I could observe the warnings, because currently, I don't see any.

**Comment by sergesheff** [comment]
This is not critical warning message and will appear when app is building.
It appears in Goland IDE (https://www.jetbrains.com/go/) only.
For example if to use a Visual Studio Code this warning will not appear.
![warning](https://user-images.githubusercontent.com/10615997/213249725-f3d39f26-a0f6-4829-b2b7-245c2dc6f81b.png)

**Comment by amotl** [comment]
Thanks, Sergey. GH-122 resolves this detail for me. Let me know about any other flaws you might discover.
